### PR TITLE
Add The Ability to Disable Kebab Casing

### PR DESCRIPTION
**Pull request by onairmarc**
This PR adds the ability for users of this package to disable kebab casing.

### CODE REVIEW

**Comment by onairmarc** [comment]
@inxilpro for some reason, the last 9 workflows are still pending. Not exactly sure why. I didn't know GitHub had different run groups for GHA. 🤷🏻‍♂️

**Comment by inxilpro** [comment]
OK. I reverted the whitespace changes, but now that I look the PR I have some concerns. Before I bring them up, though, what are you hoping to achieve with this? Do you prefer a *different* casing standard, other than kebab? Or do you actually have a scenario where you would like whatever is passed to the command?

I think the better way to approach this would be to introduce a config variable that defaults to `kebab` but accepts `studly` and `camel` and `snake` as options. That way if you prefer studly case, you can configure it once. Would that suit your needs?

**Comment by inxilpro** [comment]
I updated the PR to allow for more naming configurations, but I'm not 100% sure you would want to do this…  If you browse the [first 10-15 pages of Packagist's most popular packages](https://packagist.org/explore/popular) there isn't a single one that's camel- or studly-cased (and only a couple that are snake-case).

**Comment by onairmarc** [comment]
For the purposes of external packages, yes, I'd agree that kebab case would more than likely be the go-to for package naming. However, the `make:module` command is also generating directories in kebab case which is what this PR aims to allow the user to disable.

**Comment by inxilpro** [comment]
> However, the `make:module` command is also generating directories in kebab case which is what this PR aims to allow the user to disable.

So, given a module called "Shopping Cart" and a company named "Galactic Empire" would your preference be:

- path: `Modules/shoppingCart`
- composer name: `galactic-empire/shopping-cart`
- namespace: `GalacticEmpire\ShoppingCart`

?

**Comment by onairmarc** [comment]
> OK. I reverted the whitespace changes, but now that I look the PR I have some concerns. Before I bring them up, though, what are you hoping to achieve with this? Do you prefer a _different_ casing standard, other than kebab? Or do you actually have a scenario where you would like whatever is passed to the command?
> 
> I think the better way to approach this would be to introduce a config variable that defaults to `kebab` but accepts `studly` and `camel` and `snake` as options. That way if you prefer studly case, you can configure it once. Would that suit your needs?

I think this is a much better solution than the one I submitted!

**Comment by onairmarc** [comment]
> > However, the `make:module` command is also generating directories in kebab case which is what this PR aims to allow the user to disable.
> 
> So, given a module called "Shopping Cart" and a company named "Galactic Empire" would your preference be:
> 
> * path: `Modules/shoppingCart`
> * composer name: `galactic-empire/shopping-cart`
> * namespace: `GalacticEmpire\ShoppingCart`
> 
> ?

Path: `Modules\ShoppingCart`
Composer Name: `galacticempire/shoppingcart`
Namespace: `GalacticEmpire\ShoppingCart`

**Comment by onairmarc** [comment]
@inxilpro is there any movement on this? Is there anything I can do to help get this into a mergable state?

**Pull request closed without merging**
