### PR TITLE
FIX deprecated function signature

### PR DESCRIPTION
**Pull request by da-mask**
In php8.3 `ReflectionProperty::setValue()` requires a second argument. I'm not sure if this fix is correct, but looks like we are unsetting a static property, so this might be ok ?

### CODE REVIEW

**Comment by inxilpro** [comment]
@da-mask it looks like your branch isn't set up to allow me to push changes to it. If you want to change this to match #90 I'm happy to merge your PR. Otherwise, I'll close this and merge #90.

**Comment by da-mask** [comment]
@inxilpro Thanks for allowing me the opportunity to take the glory. I've updated my branch.

**Comment by inxilpro** [comment]
@da-mask can you update from main? We have branch protections enabled that don't allow merging out of date code.

**Comment by da-mask** [comment]
@inxilpro Sorry, I thought I had ..? If I've made a mess, maybe just bring back #90 and merge that. Thanks again.

**Comment by inxilpro** [comment]
@da-mask thanks!

**Pull request merged**
